config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'static_pages#index'
  get 'static_pages/secret'

    resources :attendances
  resources :events
  resources :users
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	#after_create :confirmation_send

  belongs_to :participant, class_name: 'User'
  belongs_to :event

  private

  def confirmation_send
    AttendanceMailer.confirmation_email(self).deliver_now
  end
end

app/models/event.rb
class Event < ApplicationRecord
#	after_create :confirmation_send
	
  belongs_to :admin, class_name: 'User'
  has_many :attendances
  has_many :participants, class_name: 'User', through: :attendances

  #validates :start_date, presence: true, start_date: true
  #validates :duration, presence: true, duration: true
  validates :title, presence: true, length: { in: 5..140 }
  validates :description, presence: true, length: { in: 20..1000 }
  validates :price, presence: true, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 1000 }
  validates :location, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :welcome_send

	has_many :events, foreign_key: 'admin_id', class_name: 'Event'
  has_many :attendances, foreign_key: 'participant_id', class_name: 'Attendance'
  
  private

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_devise_parameters, if: :devise_controller?

	def configure_devise_parameters
		devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation)}
		devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation)}
	end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
  end

  def create
    event_params = params.require(:event).permit(
      :start_date,
      :duration,
      :title,
      :description,
      :price,
      :location
    )
    @event = Event.new(event_params)
    @event.admin = current_user
    if @event.save
      flash[:success] = "L'événement a bien été créé !"
      redirect_to event_path(@event.id)
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  before_action :authenticate_user!, only: [:secret]


  def index
  end

  def secret
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = current_user
  end

  def new
    @user = User.new
  end

  def create
  end

  def edit
    @user = current_user
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/create.html.erb
<h1>Attendances#create</h1>
<p>Find me in app/views/attendances/create.html.erb</p>

app/views/attendances/destroy.html.erb
<h1>Attendances#destroy</h1>
<p>Find me in app/views/attendances/destroy.html.erb</p>

app/views/attendances/edit.html.erb
<h1>Attendances#edit</h1>
<p>Find me in app/views/attendances/edit.html.erb</p>

app/views/attendances/index.html.erb
<h1>Attendances#index</h1>
<p>Find me in app/views/attendances/index.html.erb</p>

app/views/attendances/new.html.erb
<h1>Attendances#new</h1>
<p>Find me in app/views/attendances/new.html.erb</p>

app/views/attendances/show.html.erb
<h1>Attendances#show</h1>
<p>Find me in app/views/attendances/show.html.erb</p>

app/views/attendances/update.html.erb
<h1>Attendances#update</h1>
<p>Find me in app/views/attendances/update.html.erb</p>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>

<h1>Voici les évènements à venir</h1>
<h2> Tu peux en créer un en allant ici</h2>
<button type="button" class="btn btn-secondary btn-lg btn-block"><%= link_to "Créer son évènement", new_event_path %></button>
	<div class="row">
    <%@events.each do |event|%>
      <!-- event-->
      <div class="col-sm-2">
      	
      </div>
      <div class="col-sm-2">
			
		</div>
      <div class='col-sm-2 event-tab'>
        <div class="list-group" role='tablist'>
          <a href="<%= event_path(event.id)%>" class="list-group-item list-group-item-action not_like" role='tab'>
            <div class="d-flex w-80 justify-content-between">
              <h5 class="mb-1 text-left"><%= event.title%></h5>
            </div>
            <div class="d-flex w-80 justify-content-between">
              <small class='mb-1'><%= event.start_date%></small>
            </div>
          </a>
        </div>
      </div>
    <% end %>
  </div>

 	</div>
  </div>
</div>

app/views/events/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>

      	<h1>Création d'évènemennt</h1>
      	
     

      </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>

      	<h2><%=@event.title %></h2>
      	
     <div class="card-body">
          <p class="card-text"><strong>Description : </strong><%= @event.description %></p>
          <p class="card-text"><strong>Nombre de Participants : </strong><%= @event.attendances.count %></p>

          <p class="card-text"><strong>Prix : </strong><%= @event.price %> €</p>
          <p class="card-text"><strong>Lieu de l'événement : </strong><%= @event.location %></p>
        </div>

      </div>
  </div>
</div>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Event</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%unless user_signed_in? %>
    <nav class="navbar navbar-light bg-light">
        <div class="navbar-brand"><%= link_to "Home", root_path %></div>
    </nav>
    <% end %>

    <% if user_signed_in?%>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <div class="navbar-brand"><%= link_to "Home", root_path %></div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= events_path %>">Event</a>
      </li>
     
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         Ton profil
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="<%=user_path(current_user.id)%>">Voir son profil</a>
          <a class="dropdown-item" href="<%=edit_user_registration_path%>">Editer son compte</a>
          <a class="dropdown-item" href="<%=static_pages_secret_path%>">Essaye on sait jamais :)</a>
        </div>
      </li>
    </ul>
  </div>
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><%= link_to "Se déconnecter", destroy_user_session_path, method: :delete %></button>
</nav>
    <% end%>
 

    
    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<p><h1><Salut </h1>
     
    <p> Tu trouvera ici les évènements qui existent </p>
  <% if user_signed_in? %>
  	<div class="container">
  		<div class="row">
    		<div class="col-lg-6 offset-sm-1">
      <br><br><br>
    

    <li>
      <%= link_to "Evènement", events_path %>
    </li>
		<br/>
    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

      
   			</div>
 		 </div>
	</div>


  <% else %>

<div class="jumbotron jumbotron-fluid">
  <div class="container">
  	<h1 class="display-4">Bienvenue sur notre site de création d'évènement</h1>
  	<p class="lead">Si tu recherches des évènements sur Lyon c'est ici !!</p>
    <button type="button" class="btn btn-outline-secondary"><%= link_to "S'inscrire", new_user_registration_path %></button>

	<button type="button" class="btn btn-outline-primary"><%= link_to 'Se connecter', new_user_session_path %></button>
  <% end %>	
</p>

app/views/static_pages/secret.html.erb
<div class=jumbotron>
 <div class=container>
 <h1>MEILLEUR FETE DU MONDE</h1>
 <img src="http://admin.traxmag.com//uploads/images/croped600x1200/2017/07/Jour_3_-_NS_Days_2_-_NS_2017_-_Nina_Kraviz_-_26_05_2017_BD%C2%A9b-rob.com-1_596e170e304ef.jpg" alt="" />
 </div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>
  
<ul class="list-group">
  <li class="list-group-item">Ton profil</li>
  <li class="list-group-item"><%= current_user.email %></li>
  <li class="list-group-item"><%= current_user.first_name %></li>

</ul>
<li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>
  </div>
</div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>